"""
Django settings for Taskmananger project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

from pathlib import Path
import dj_database_url
import os

# Base directory

BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY SETTINGS

SECRET_KEY = 'django-insecure-zfpjblumzu73oknbwv1*780dsdh@#6v+guq96)w7vm#j9hk6(x'

DEBUG = False

ALLOWED_HOSTS = ['.onrender.com', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
'django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'Tasks',
]

MIDDLEWARE = [
'django.middleware.security.SecurityMiddleware',
'whitenoise.middleware.WhiteNoiseMiddleware',
'django.contrib.sessions.middleware.SessionMiddleware',
'django.middleware.common.CommonMiddleware',
'django.middleware.csrf.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Taskmananger.urls'

TEMPLATES = [
{
'BACKEND': 'django.template.backends.django.DjangoTemplates',
'DIRS': [BASE_DIR / 'templates'],
'APP_DIRS': True,
'OPTIONS': {
'context_processors': [
'django.template.context_processors.request',
'django.contrib.auth.context_processors.auth',
'django.contrib.messages.context_processors.messages',
],
},
},
]

WSGI_APPLICATION = 'Taskmananger.wsgi.application'

# DATABASE (Render PostgreSQL)

DATABASES = {
'default': dj_database_url.parse(
"postgresql://tasks_django_rander_user:pBKaL5sX7yHOmWzIlueSPCahI6NrkgXh@dpg-d6p97c9r0fns73e75230-a.oregon-postgres.render.com/tasks_django_rander",
conn_max_age=600
)
}

# Password validation

AUTH_PASSWORD_VALIDATORS = [
{
'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
},
{
'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
},
{
'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
},
{
'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
},
]

# Internationalization

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# STATIC FILES

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / "static"]

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# MEDIA FILES

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

# EMAIL SETTINGS

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER ='shaikhaltaf1176@gmail.com'
EMAIL_HOST_PASSWORD ='kkbf pzcd mhcr vytz'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# DEFAULT AUTO FIELD

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

